name: CI

on:
  push:
    branches: [ main, task-1, task-2, task-3, task-4 ]
  pull_request:
    branches: [ main, task-1, task-2, task-3, task-4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch DVC data (if available)
        run: |
          if [ -f .dvc/config ]; then
            echo "Pulling data via DVC …";
            dvc pull -q || echo "No DVC data to pull.";
          else
            echo "DVC not initialized in this branch.";
          fi


      - name: Run tests (if any)
        run: |
          if [ -d "test" ] && [ "$(ls -A test | wc -l)" -gt 0 ]; then
            echo "Running pytest …"
            pytest -q || code=$?
            # pytest exit code 5 means "no tests collected" – treat as success
            if [ "${code:-0}" -eq 5 ]; then
              echo "No tests collected – treating as success";
              exit 0;
            elif [ "${code:-0}" -ne 0 ]; then
              exit $code;
            fi
          else
            echo "No tests found – skipping";
          fi
